name: pos_2
description: A new Flutter application.

publish_to: 'none' 

version: 1.5.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_settings: ^4.1.1
  badges: ^3.1.1
  barcode_scan2: ^4.2.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.0.0
  connectivity: ^3.0.6
  cron: ^0.4.1
  cupertino_icons: ^1.0.6
  date_time_picker: ^2.1.0
  dio: ^5.4.0
  flutter_html_to_pdf: ^0.7.0
  fluttertoast: ^8.2.4
  geolocator: 8.2.1
  get_ip_address: ^0.0.6
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  http: ^0.13.6
  image_picker: ^1.0.4
  material_design_icons_flutter: ^5.0.6996
  path_provider: ^2.1.1
  pdf: ^3.10.1
  permission_handler: ^9.0.2
  printing: ^5.11.0
  provider: ^6.1.1
  qr: ^3.0.1
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  search_choices: ^2.2.7
  share: ^2.0.4
  syncfusion_flutter_datepicker: ^24.1.41
  url_launcher: ^6.2.5
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/TM Tech POS.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - i18n/
